ARG JAVA17_IMAGE=eclipse-temurin:17-jre
FROM ${JAVA17_IMAGE}

WORKDIR /app

ARG JAR_FILE
COPY ${JAR_FILE} /app/app.jar

ENV JAVA_OPTS="" \
    TZ=Asia/Shanghai

ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar /app/app.jar"]
