# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER Integrity-Supervision-Platform

# 挂载目录
VOLUME /home/integrity
# 创建目录
RUN mkdir -p /home/integrity
# 指定路径
WORKDIR /home/integrity
# 复制jar文件到路径
COPY ./jar/integrity-modules-system.jar /home/integrity/integrity-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","integrity-modules-system.jar"]